### ISSUE TITLE
Create py37 feedstock

### ISSUE THREAD

**Issue by greglucas** [conda-forge/ipympl-feedstock#19]
Issue:

ipympl needs to be updated with a build version for Python 3.7. Currently conda-forge selects the py_0 build associated with version 0.0.8. This attempts to downgrade Python in the environment. This came up in this issue: https://github.com/matplotlib/jupyter-matplotlib/issues/41

I couldn't figure out what needs to be updated in the repository to submit a pull request.

**Comment by pdeitel** [comment]
Can we also get a build of https://github.com/matplotlib/jupyter-matplotlib in conda-forge for 3.7?

**Comment by blink1073** [comment]
I tried to do this in #22 manually, but it looks like we have to wait for the autotick-bot in order to pick up Py3.7.

**Comment by michaelaye** [comment]
I'm confused, what is the difference between juptyer-matplotlib and ipympl? I thought there were the same? Then again, I'm also confused if I should do now %matplotlib ipympl or %matplotlib widget. So many changes recently...

**Comment by michaelaye** [comment]
Is the autotick-bot that slow? 28 days?

**Comment by michaelaye** [comment]
this seems to be done now.
